apiVersion: platform.kratix.io/v1alpha1
kind: AppModelARequest
metadata:
  name: ${{values.uniqueName}}
  namespace: ${{values.requestNamespace}}
spec:
  app:
    name: "${{values.appName}}"
    image: "${{values.image}}"
    imagePullPolicy: "${{values.imagePullPolicy}}"
    port: ${{values.port}}
    replicas: ${{values.replicas}}
    serviceType: "${{values.serviceType}}"
  target:
    namespace: "${{values.targetNamespace}}"
  gateway:
    enabled: ${{values.gatewayEnabled}}
    {% if values.gatewayEnabled %}path: "${{values.gatewayPath}}"
    tls: ${{values.gatewayTls}}{% endif %}
  storage:
    enabled: ${{values.storageEnabled}}
    {% if values.storageEnabled %}size: "${{values.storageSize}}"
    mountPath: "${{values.storageMountPath}}"
    storageClass: "${{values.storageClass}}"{% endif %}
  database:
    enabled: ${{values.databaseEnabled}}
    {% if values.databaseEnabled %}type: "${{values.databaseType}}"
    storageGB: ${{values.databaseStorageGB}}
    instanceSize: "${{values.databaseInstanceSize}}"{% endif %}